//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment.Web.Mvc.Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataAnnotationsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataAnnotationsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Employment.Web.Mvc.Infrastructure.Properties.DataAnnotationsResources", typeof(DataAnnotationsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid Australian Business Number (ABN)..
        /// </summary>
        public static string AbnAttribute_Invalid {
            get {
                return ResourceManager.GetString("AbnAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not have a valid selection..
        /// </summary>
        public static string AdwSelectionAttribute_Invalid {
            get {
                return ResourceManager.GetString("AdwSelectionAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains words that are deemed inappropriate..
        /// </summary>
        public static string BlueWordAttribute_Invalid {
            get {
                return ResourceManager.GetString("BlueWordAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains words that are deemed inappropriate. These words are: {1}..
        /// </summary>
        public static string BlueWordAttribute_InvalidWithBlueWords {
            get {
                return ResourceManager.GetString("BlueWordAttribute_InvalidWithBlueWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be selected..
        /// </summary>
        public static string BoolMustBeTrueAttribute_Invalid {
            get {
                return ResourceManager.GetString("BoolMustBeTrueAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid because of {1}..
        /// </summary>
        public static string ContingentValidationAttribute_Invalid {
            get {
                return ResourceManager.GetString("ContingentValidationAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid Customer Reference Number (CRN)..
        /// </summary>
        public static string CrnAttribute_Invalid {
            get {
                return ResourceManager.GetString("CrnAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is in an invalid format..
        /// </summary>
        public static string EmailAddressAttribute_Invalid {
            get {
                return ResourceManager.GetString("EmailAddressAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid file..
        /// </summary>
        public static string FileAttribute_Invalid {
            get {
                return ResourceManager.GetString("FileAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {1} bytes or less when compressed..
        /// </summary>
        public static string FileAttribute_InvalidCompressedSize {
            get {
                return ResourceManager.GetString("FileAttribute_InvalidCompressedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded for {0} must have a valid file extension for a {1} file..
        /// </summary>
        public static string FileAttribute_InvalidExtension {
            get {
                return ResourceManager.GetString("FileAttribute_InvalidExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a configured FileModel for file type {0}..
        /// </summary>
        public static string FileAttribute_InvalidFileModels {
            get {
                return ResourceManager.GetString("FileAttribute_InvalidFileModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not contain any images..
        /// </summary>
        public static string FileAttribute_InvalidRtfImage {
            get {
                return ResourceManager.GetString("FileAttribute_InvalidRtfImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not contain any objects..
        /// </summary>
        public static string FileAttribute_InvalidRtfObject {
            get {
                return ResourceManager.GetString("FileAttribute_InvalidRtfObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid {1} file..
        /// </summary>
        public static string FileAttribute_InvalidSignature {
            get {
                return ResourceManager.GetString("FileAttribute_InvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {1} or less..
        /// </summary>
        public static string FileAttribute_InvalidSize {
            get {
                return ResourceManager.GetString("FileAttribute_InvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a {1} file..
        /// </summary>
        public static string FileAttribute_InvalidType {
            get {
                return ResourceManager.GetString("FileAttribute_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {1} {2}..
        /// </summary>
        public static string IsAttribute_Invalid {
            get {
                return ResourceManager.GetString("IsAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} must implement {1}..
        /// </summary>
        public static string MaxAttribute_ArbitraryTypeNotIComparable {
            get {
                return ResourceManager.GetString("MaxAttribute_ArbitraryTypeNotIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than or equal to {1}..
        /// </summary>
        public static string MaxAttribute_Invalid {
            get {
                return ResourceManager.GetString("MaxAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value must be set..
        /// </summary>
        public static string MaxAttribute_Must_Set_Maximum {
            get {
                return ResourceManager.GetString("MaxAttribute_Must_Set_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type must be set when a string is used for the maximum value..
        /// </summary>
        public static string MaxAttribute_Must_Set_Operand_Type {
            get {
                return ResourceManager.GetString("MaxAttribute_Must_Set_Operand_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} must implement {1}..
        /// </summary>
        public static string MinAttribute_ArbitraryTypeNotIComparable {
            get {
                return ResourceManager.GetString("MinAttribute_ArbitraryTypeNotIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}..
        /// </summary>
        public static string MinAttribute_Invalid {
            get {
                return ResourceManager.GetString("MinAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum value must be set..
        /// </summary>
        public static string MinAttribute_Must_Set_Minimum {
            get {
                return ResourceManager.GetString("MinAttribute_Must_Set_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type must be set when a string is used for the minimum value..
        /// </summary>
        public static string MinAttribute_Must_Set_Operand_Type {
            get {
                return ResourceManager.GetString("MinAttribute_Must_Set_Operand_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a maximum length of {1}..
        /// </summary>
        public static string NumericLengthAttribute_Invalid {
            get {
                return ResourceManager.GetString("NumericLengthAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a minimum length of {2} and a maximum length of {1}..
        /// </summary>
        public static string NumericLengthAttribute_InvalidWithMinimumLength {
            get {
                return ResourceManager.GetString("NumericLengthAttribute_InvalidWithMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}..
        /// </summary>
        public static string RangeAttribute_Invalid {
            get {
                return ResourceManager.GetString("RangeAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required because {1} is {2} {3}..
        /// </summary>
        public static string RequiredIfAttribute_Invalid {
            get {
                return ResourceManager.GetString("RequiredIfAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required because {1} is empty..
        /// </summary>
        public static string RequiredIfEmptyAttribute_Invalid {
            get {
                return ResourceManager.GetString("RequiredIfEmptyAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required because {1} is not empty..
        /// </summary>
        public static string RequiredIfNotEmptyAttribute_Invalid {
            get {
                return ResourceManager.GetString("RequiredIfNotEmptyAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one type of IsID property can be used in a single RequiredParameter attribute..
        /// </summary>
        public static string RequiredParameterAttribute_Invalid {
            get {
                return ResourceManager.GetString("RequiredParameterAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains invalid characters..
        /// </summary>
        public static string SpecialCharactersAttribute_Invalid {
            get {
                return ResourceManager.GetString("SpecialCharactersAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains invalid characters. These characters are: {1}..
        /// </summary>
        public static string SpecialCharactersAttribute_InvalidWithCharacters {
            get {
                return ResourceManager.GetString("SpecialCharactersAttribute_InvalidWithCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page has expired as a newer version is open or the form has been submitted more than once (clicking more than once will result in slower response times)..
        /// </summary>
        public static string ValidateAntiDuplicateSubmitTokenAttribute_Invalid {
            get {
                return ResourceManager.GetString("ValidateAntiDuplicateSubmitTokenAttribute_Invalid", resourceCulture);
            }
        }
    }
}
