//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrophyDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        public Competition()
        {
            this.Winners = new HashSet<Winner>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Frequency { get; set; }
    
        public virtual Competition Competition1 { get; set; }
        public virtual Competition Competition2 { get; set; }
        public virtual ICollection<Winner> Winners { get; set; }
    }
}
