//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrophyDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Winner
    {
        public int Id { get; set; }
        public string When { get; set; }
        public int Sequence { get; set; }
        public string Name { get; set; }
        public int CompetitionId { get; set; }
    
        public virtual Competition Competition { get; set; }
    }
}
